[package]
name = "artificial_benevolence"
version = "0.1.0"
authors = ["Yuurai"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "develop" }
lazy_static = "1.1.0"
itertools = "0.7.8"
rand = "0.5.5"